### ISSUE TITLE
working on Xamarin

### ISSUE THREAD

**Issue by ktngoykalolo** [JaCraig/Structure.Sketching#31]
Is the library working on Xamarin?

**Comment by JaCraig** [comment]
In theory it should but I don't have the test framework set up for xamarin or unity yet. Both are on the list but consider the library at beta stage at the moment.

**Comment by ktngoykalolo** [comment]
I will test first and see the results.

**Comment by JaCraig** [comment]
Used it on a couple of apps now, definitely working on Xamarin. Still need the automated tests though.
