### ISSUE TITLE
Updating the library to .NET Standard 2.1 or .NET 6

### ISSUE THREAD

**Issue by tzinmein** [JaCraig/Structure.Sketching#49]
Hi James, I used Structure.Sketching in a hobby project of mine. I recently looked into reviving the project and updating it from .NET core 1.1 to .NET 6, and noted that this library hasn't been updated since I first used it.

If it's OK with you, I'll keep my fork updated and available publicly.

**Comment by JaCraig** [comment]
Go for it. My focus switched from vision and AI based around images to data analysis/text based AI a couple years ago. If you wanted to, you could use one of the other libraries as a base and just migrate the filters. I'd say those are the most useful bits of code. When I revisit this library that's probably what I'll end up doing.

**Comment by tzinmein** [comment]
Great, thank you!
